### ISSUE TITLE
Association

### ISSUE THREAD

**Issue by Manju244** [addywaddy/couchsurfer#1]
1) How can we refer variable name from one class to another class?

2) class BlockIP
  include CouchSurfer::Model
  include CouchSurfer::Associations

  key_accessor :ip_number, :ip_range

  has_many :ip_number, :class_name => :Firewallmain,
   :view => :ip_no
   :query => lambda{ {:key => [ip_number]} }
end

So i am creating a view using query but its not working?

3) describe CouchSurfer::Associations do
    before(:all) do
     db = CouchRest.database!('firewall01')
     db.delete!

error :  undefined method `describe' for main:Object (NoMethodError)
Give me the solution
and more about association?

**Comment by addywaddy** [comment]
sorry for the late reply :)
1. not sure what you mean here. Can you provide an example?
2. When you say 'not working' what do you mean? no results, error, incorrect results?
3. you need the rspec gem to run the tests. rspec defines the method "describe"
